version: '3'

services:

  db:
    image: mysql:8.0.20
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --transaction-isolation=READ-COMMITTED 
      - --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: wiki-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      TZ: Asia/Shanghai
    expose:
      - 3306
    networks:
      - custom_net
    volumes:
      - ./db-data:/var/lib/mysql

  confluence:
    image: atlassian/confluence-server
    container_name: wiki-confluence
    environment:
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 8090:8090
    networks:
      - custom_net
    volumes:
      - ./confluence-data:/var/atlassian/application-data/
      - ./mysql-connector-java-8.0.20.jar:/opt/atlassian/confluence/confluence/WEB-INF/lib/mysql-connector-java-8.0.20.jar

  jira:
    image: atlassian/jira-software
    container_name: wiki-jira
    environment:
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 8092:8080
    volumes:
      - ./jira-data:/var/atlassian/application-data/
      - ./mysql-connector-java-8.0.20.jar:/opt/atlassian/jira/lib/mysql-connector-java-8.0.20.jar
    networks:
      - custom_net

networks:
  custom_net:
    external:
      name: mynetwork
