version: "3.9" 
services:
  rabbitmq:
    image: rabbitmq:management
    restart: always     
    container_name: rabbitmq
    ports: 
      - 15672:15672
      - 5672:5672
    networks:
      - custom_net
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    volumes:
      - ./data:/var/lib/rabbitmq

networks:
  custom_net:
    external: 
      name: mynetwork
