version: '3.9'
services:
  activemq:
    image: webcenter/activemq
    restart: always
    container_name: activemq
    ports:
      - 61613:61613
      - 61616:61616
      - 8161:8161
    volumes:
      - ./data:/data/activemq
      - ./log:/var/log/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_CONFIG_MINMEMORY=512
      - ACTIVEMQ_CONFIG_MAXMEMORY=2048
      - TZ=Asia/Shanghai