version: '3.9'
services:
  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: always
    ports:
      - "8082:8081"
    volumes:
      - ./data:/nexus-data
    environment:
      TZ: Asia/Shanghai
    networks:
      - custom_net

networks:
  custom_net:
    external:
      name: mynetwork